### ISSUE TITLE
Next 앱에서 로컬 폰트 파일 적용하기

### ISSUE THREAD

**Issue by soonitoon** [soonitoon/TIL#12]
`src/fonts` 경로에 폰트 파일을 적용하면 불러올 수 없다.

- 프로젝트 최상단 `public/fonts` 폴더에 폰트 파일을 넣는다.
- `_document` 파일 헤더 안에서 `<link />` 태그를 통해 폰트 파일을 불러온다.

```javascript
 <Html>
      <Head>
        <link
          rel="preload"
          href="/fonts/PretendardVariable.woff2"
          as="font"
          crossOrigin=""
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
```

- 글로벌 스타일에 폰트 페이스를 정의한다.

```css
@font-face {
    font-family: 'Pretendard Variable';
    font-weight: 45 920;
    font-style: normal;
    font-display: swap;
    src: local('Pretendard Variable'),
      url('/fonts/PretendardVariable.woff2') format('woff2-variations');
  }
```
