### ISSUE TITLE
enabled, disabled 상태에 따라 서로 다른 스타일 지정하기

### ISSUE THREAD

**Issue by soonitoon** [soonitoon/TIL#21]
활성 여부에 따라 자바스크립트로 조건부 스타일을 줄 필요 없이, CSS의 `:enabled`, `:disabled` 선택자를 사용하면 된다.

```css
.button {
  width: 200px;
  height: 50px;

  &:enabled {
    color: red;
  }

  &:disabled {
    color: green;
  }
}
```
