### ISSUE TITLE
next/image에서 이미지의 원본 비율 유지하며 부모 요소에 꽉 채우기

### ISSUE THREAD

**Issue by soonitoon** [soonitoon/TIL#26]
- `Image` 컴포넌트의 `layout` 속성에 `fill`을 주고, `objectFit` 속성에 `cover`를 주어 원래 비율을 유지하며 부모 요소에 꽉 차게 만든다.
- `Image` 컴포넌트의 부모 태그 스타일에 `position: relative` 속성을 주고, `width`와 `height`로 이미지의 크기를 결정한다.

```js
<div>
        <Image
          src={DEMO_GROUP_IMAGE_URL}
          layout="fill"
          objectFit="cover"
          alt="모임 프로필"
        />
</div>
```

```css
div {
  position: relative;
  width: 100px;
  height: 100px;
}
```
