### ISSUE TITLE
CSS로 스타일은 그대로 두면서 버튼 터치/클릭 영역 넓히기

### ISSUE THREAD

**Issue by soonitoon** [soonitoon/TIL#27]
페이지 내에서 작은 크기의 버튼이나 링크를 써야할 때 넓히고 싶은 터치 영역만큼 `padding` 값을 준 후, `margin`으로 같은 값을 음수로 주면 스타일을 유지한 상태로 터치 영역만 넓힐 수 있다.

```css
.button {
  padding: 10px;
  margin: -10px;
}
```

<img width="292" alt="image" src="https://user-images.githubusercontent.com/71015915/186680843-7b2e7f92-0926-432b-b6ea-153d34bbf3d5.png">
