### ISSUE TITLE
:disabled 상태인 버튼은 동시에 :active 상태도 가질 수 있다.

### ISSUE THREAD

**Issue by soonitoon** [soonitoon/TIL#30]
```html
<button disabled>버튼</button>
```
- 위처럼 `disabled` 상태인 버튼은 눌러도 작동하지 않으며, CSS에서 `:disabled` 가상 선택자로 선택할 수 있다.
- 하지만 작동하지 않는 버튼이라도 `:active` 상태는 가질 수 있다. 따라서 버튼을 눌렀을 때 다른 스타일을 적용했다면 비활성화된 버튼임에도 불구하고 클릭 효과가 나타나게 된다.
- 이를 막기 위해서는 `:enabled:active`처럼 활성 상태인 버튼에만 active 상태일 때의 스타일을 주어야 한다.

```css
button:enabled:active {
  background-color: red;
}
```
